#ifndef CONFIG_H
#define CONFIG_H

#define HAVE_SIZE_T
#define HAVE_INET_NTOA
#define HAVE_STRUCT_TIMEVAL
#define HAVE_SYS_STAT_H
#define OPENSSL_PRNG_ONLY
#define NO_IPPORT_RESERVED_CONCEPT
#define MISSING_NFDBITS
#define MISSING_FD_MASK
#define MISSING_HOWMANY
#define HAVE_STRUCT_SOCKADDR_STORAGE
#define HAVE_STRUCT_IN6_ADDR
#define HAVE_STRUCT_SOCKADDR_IN6
#define HAVE_GETADDRINFO
#define HAVE_FREEADDRINFO
#define HAVE_STRUCT_ADDRINFO
#define HAVE_GETNAMEINFO
#define IP_TOS_IS_BROKEN
#define HAVE_GAI_STRERROR
#define SNPRINTF_CONST const
#define HAVE_EVP_SHA256
#define HAVE_DECL_SHUT_RD 0
#define HAVE___FUNCTION__
#define HAVE_SIG_ATOMIC_T
#define HAVE_SELECT

/* DUMMY... */
#define HAVE_GETGROUPLIST
#define HAVE_GETPEEREID
#define HAVE_UTIMES
#define HAVE_TCGETPGRP
#define HAVE_NANOSLEEP
#define HAVE_TRUNCATE
#define GETPGRP_VOID
#define HAVE_OPENPTY

#endif /* CONFIG_H */
